// constants/sidebar.ts
import {
    Home,
    BookOpen,
    Calendar,
    BarChart2,
    MessageCircle,
    CreditCard,
    FileText,
    LogOut,
    Users,
    User,
    Plus,
} from "lucide-react";
import { SidebarItem } from "../types/sidebar";
import { Permission } from "../enums/permissions";

export const PARENT_MENU_ITEMS: SidebarItem[] = [
    {
        label: "Dashboard",
        tab: "dashboard",
        href: "/frontend/pages/parent?tab=dashboard",
        icon: Home,
        permission: Permission.DASHBOARD,
    },
    {
        label: "Homework",
        tab: "homework",
        href: "/frontend/pages/parent?tab=homework",
        icon: BookOpen,
        permission: Permission.HOMEWORK,
    },
    {
        label: "Attendance",
        tab: "attendance",
        href: "/frontend/pages/parent?tab=attendance",
        icon: Calendar,
        permission: Permission.ATTENDANCE,
    },
    {
        label: "Marks",
        tab: "marks",
        href: "/frontend/pages/parent?tab=marks",
        icon: BarChart2,
        permission: Permission.MARKS,
    },
    {
        label: "Chat",
        tab: "chat",
        href: "/frontend/pages/parent?tab=chat",
        icon: MessageCircle,
        permission: Permission.CHAT,
    },
    {
        label: "Fees",
        tab: "fees",
        href: "/frontend/pages/parent?tab=fees",
        icon: CreditCard,
        permission: Permission.FEES,
    },
    {
        label: "Certificates",
        tab: "certificates",
        href: "/frontend/pages/parent?tab=certificates",
        icon: FileText,
        permission: Permission.CERTIFICATES,
    },
    {
        label: "Logout",
        icon: LogOut,
        action: "logout",
    },
];


export const SCHOOLADMIN_MENU_ITEMS: SidebarItem[] = [
    {
        label: "Dashboard",
        tab: "dashboard",
        href: "/frontend/pages/schooladmin",
        icon: Home,
        permission: Permission.DASHBOARD,
    },
    {
        label: "Classes",
        tab: "classes",
        href: "/frontend/pages/schooladmin?tab=classes",
        icon: BookOpen,
        permission: Permission.CLASSES,
    },
    {
        label: "Students",
        tab: "students",
        href: "/frontend/pages/schooladmin?tab=students",
        icon: Users,
        permission: Permission.STUDENTS,
    },
    {
        label: "Add User",
        tab: "add-user",
        href: "/frontend/pages/schooladmin?tab=add-user",
        icon: Plus,
        permission: Permission.NEW_USER,
    }, {
        label: "Student Details",
        tab: "student-details",
        href: "/frontend/pages/schooladmin?tab=student-details",
        icon: Users,
        permission: Permission.STUDENT_DETAILS,
    },
    {
        label: "Teachers",
        tab: "teachers",
        href: "/frontend/pages/schooladmin?tab=teachers",
        icon: User,
        permission: Permission.TEACHERS,
    },
    {
        label: "Teacher Leaves",
        tab: "teacher-leaves",
        href: "/frontend/pages/schooladmin?tab=teacher-leaves",
        icon: Calendar,
        permission: Permission.TEACHER_LEAVES,
    },
    {
        label: "Teacher Audit",
        tab: "teacher-audit",
        href: "/frontend/pages/schooladmin?tab=teacher-audit",
        icon: FileText,
        permission: Permission.TEACHER_AUDIT,
    },
    {
        label: "Workshops & Events",
        tab: "workshops",
        href: "/frontend/pages/schooladmin?tab=workshops",
        icon: Calendar,
        permission: Permission.WORKSHOPS,
    },
    {
        label: "Newsfeed",
        tab: "newsfeed",
        href: "/frontend/pages/schooladmin?tab=newsfeed",
        icon: FileText,
        permission: Permission.NEWSFEED,
    }, {
        label: "Circulars",
        tab: "circulars",
        href: "/frontend/pages/schooladmin?tab=circulars",
        icon: FileText,
        permission: Permission.CIRCULARS,
    },
    {
        label: "Certificate Request",
        tab: "certificates",
        href: "/frontend/pages/schooladmin?tab=certificates",
        icon: FileText,
        permission: Permission.CERTIFICATES,
    },
    {
        label: "Fees",
        tab: "fees",
        href: "/frontend/pages/schooladmin?tab=fees",
        icon: CreditCard,
        permission: Permission.FEES,
    },
    {
        label: "Exams",
        tab: "exams",
        href: "/frontend/pages/schooladmin?tab=exams",
        icon: FileText,
        permission: Permission.EXAMS,
    },
    {
        label: "Analysis",
        tab: "analysis",
        href: "/frontend/pages/schooladmin?tab=analysis",
        icon: BarChart2,
        permission: Permission.ANALYSIS,
    },
    {
        label: "Settings",
        tab: "settings",
        href: "/frontend/pages/schooladmin?tab=settings",
        icon: User,
        permission: Permission.SETTINGS,
    },
    {
        label: "Logout",
        icon: LogOut,
        action: "logout",
    },
];

export const SCHOOLADMIN_TAB_TITLES: Record<string, string> = {
    dashboard: "Dashboard",
    students: "Students",
    teachers: "Teachers",
    classes: "Classes",
    "teacher-leaves": "Teacher Leaves",
    "tc-approvals": "TC Approvals",
    payments: "Payments",
    workshops: "Workshops",
    newsfeed: "Newsfeed",
    exams: "Exams",
    analysis: "Analysis",
    "student-details": "Student Details",
    "add-user": "Add User",
    "teacher-audit": "Teacher Audit",
    circulars: "Circulars",
    certificates: "Certificate Requests",
    fees: "Fees",
    settings: "Settings",
};

export const TEACHER_MENU_ITEMS: SidebarItem[] = [
    {
        label: "Dashboard",
        tab: "dashboard",
        href: "/frontend/pages/teacher?tab=dashboard",
        icon: Home,
        permission: Permission.DASHBOARD,
    },
        {
        label: "Classes",
        tab: "classes",
        href: "/frontend/pages/teacher?tab=classes",
        icon: Users,
        permission: Permission.CLASSES,
    },
        {
        label: "Homework",
        tab: "homework",
        href: "/frontend/pages/teacher?tab=homework",
        icon: BookOpen,
        permission: Permission.HOMEWORK,
    },
       {
        label: "Marks",
        tab: "marks",
        href: "/frontend/pages/teacher?tab=marks",
        icon: BarChart2,
        permission: Permission.MARKS,
    },
    {
        label: "Attendance",
        tab: "attendance",
        href: "/frontend/pages/teacher?tab=attendance",
        icon: Calendar,
        permission: Permission.ATTENDANCE,
    },
    {
        label:"Exams & Syllabus",
        tab: "exams",
        href: "/frontend/pages/teacher?tab=exams",
        icon: FileText,
        permission: Permission.EXAMS,
    },
    {
        label:"Worksops & Events",
        tab: "workshops",
        href: "/frontend/pages/teacher?tab=workshops",
        icon: Calendar,
        permission: Permission.WORKSHOPS,
    },{
        label:"Newsfeed",
        tab: "newsfeed",
        href: "/frontend/pages/teacher?tab=newsfeed",
        icon: FileText,
        permission: Permission.NEWSFEED,
    },{
        label:"Parent Chat",
        tab: "chat",
        href: "/frontend/pages/teacher?tab=chat",
        icon: MessageCircle,
        permission: Permission.CHAT,
    },
    {
        label: "Leave",
        tab: "leaves",
        href: "/frontend/pages/teacher?tab=leaves",
        icon: FileText,
        permission: Permission.TEACHER_LEAVES,
    },
    {
        label:"Profile",
        tab: "profile",
        href: "/frontend/pages/teacher?tab=profile",
        icon: User,
        permission: Permission.PROFILE,
    },
    {
        label: "Settings",
        tab: "settings",
        href: "/frontend/pages/teacher?tab=settings",
        icon: User,
        permission: Permission.SETTINGS,
    },
     {
        label: "Sign Out",
        action: "logout",
        icon: LogOut,
    },
];



export const SUPERADMIN_SIDEBAR_ITEMS: SidebarItem[] = [
    {
        label: "Dashboard",
        href: "/frontend/pages/superadmin",
        tab: "dashboard",
        icon: Home,
        permission: Permission.DASHBOARD,
    },
    {
        label: "Add School",
        href: "/frontend/pages/superadmin?tab=addschool",
        tab: "addschool",
        icon: Plus,
        permission: Permission.ADD_SCHOOL,
    },
    {
        label: "Schools",
        href: "/frontend/pages/superadmin?tab=schools",
        tab: "schools",
        icon: Users,
        permission: Permission.SCHOOLS,
    },
    {
        label: "Fees Transactions",
        href: "/frontend/pages/superadmin?tab=transactions",
        tab: "transactions",
        icon: CreditCard,
        permission: Permission.FEES_TRANSACTIONS,
    },
    {
        label: "Sign Out",
        action: "logout",
        icon: LogOut,
    },
];
